# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.1
neo_version=21.1.213
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_group=com.mrbysco.spreadem
mod_id=spreadem
mod_archive_name=SpreadEm

#Publishing
mod_name=SpreadEm
curseforge_id=996969
modrinth_id=bh2ekORa

# Version
version=2.0.0

# Dependencies
jei_minecraft=1.21.1
jei_version=19.22.1.316
